services:
  - type: web
    name: flask-app
    env: python
    buildCommand: ""
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
